services:
  db:
    image: postgres:18.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  db-data:
